#!/usr/bin/env bash
# Crea symlinks de los dotfiles a ~/.config
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

link() {
    local src="$DOTFILES_DIR/$1"
    local dest="$HOME/$1"
    mkdir -p "$(dirname "$dest")"
    if [[ -e "$dest" && ! -L "$dest" ]]; then
        echo "[!] Backup: $dest -> ${dest}.bak"
        mv "$dest" "${dest}.bak"
    fi
    ln -sf "$src" "$dest"
    echo "[+] $dest -> $src"
}

link .config/alacritty/alacritty.toml
link .config/kitty/kitty.conf
link .config/hypr/hyprland.conf
link .config/hypr/hyprlock.conf
link .config/starship.toml
link .config/fontconfig/fonts.conf
link .config/nvim/lua/community.lua
link .config/nvim/lua/lazy_setup.lua
link .config/nvim/lua/polish.lua
link .config/nvim/lua/plugins/astrocore.lua
link .config/nvim/lua/plugins/astrolsp.lua
link .config/nvim/lua/plugins/astroui.lua
link .config/nvim/lua/plugins/mason.lua
link .config/nvim/lua/plugins/none-ls.lua
link .config/nvim/lua/plugins/treesitter.lua
link .config/nvim/lua/plugins/user.lua
link .config/rofi/config.rasi
link .config/rofi/colors.rasi
link .config/waybar/config.jsonc
link .config/waybar/style.css
link .config/waybar/colors.css
link .config/kitty/matugen.conf
link .config/alacritty/matugen.toml

# ── ghostty (config versioned; theme.conf generated by theme-switch, like kitty) ──
link .config/ghostty/config
link .config/ghostty/theme.conf
link .config/hypr/colors.conf
link .config/hypr/hyprlock-colors.conf

# ── sway rice (Debian / Wayland) ──
link .config/sway/config
link .config/swaylock/config

# ── zellij (config.kdl versioned; themes/rice.kdl is generated by theme-switch) ──
link .config/zellij/config.kdl

# ── herdr ──
link .config/herdr/config.toml

# ── claude code status line ──
link .claude/statusline.sh
chmod +x "$HOME/.claude/statusline.sh"

link .zshrc

# ── wallpapers ──
# Symlinked, not copied: the palettes in themes/ are matugen-derived from these
# exact images, so they have to travel with the repo. Symlinks keep a single
# copy on disk and leave ~/Pictures/wallpapers open for your own additions,
# which Mod+w will still pick up.
mkdir -p "$HOME/Pictures/wallpapers"
for wall in "$DOTFILES_DIR"/wallpapers/*; do
    [ -e "$wall" ] || continue
    dest="$HOME/Pictures/wallpapers/$(basename "$wall")"
    ln -sf "$wall" "$dest"
    echo "[+] $dest -> $wall"
done
