$matugen_primary = rgba(fabd2fff)
$matugen_on_primary = rgba(282828ff)
$matugen_secondary = rgba(8ec07cff)
$matugen_surface = rgba(1d2021ff)
$matugen_outline_variant = rgba(504945aa)
$matugen_error = rgba(fb4934ff)
