$hyprlock_accent = rgba(250, 189, 47, 0.8)
$hyprlock_surface = rgba(29, 32, 33, 0.9)
$hyprlock_text = rgb(235, 219, 178)
$hyprlock_text_dim = rgba(235, 219, 178, 0.8)
$hyprlock_check = rgba(142, 192, 124, 0.8)
$hyprlock_fail = rgba(251, 73, 52, 0.8)
$hyprlock_warn = rgba(254, 128, 25, 0.8)
