#!/usr/bin/env bash
#
# theme-switch.sh — single source of truth theme switcher for the sway rice.
# Reads one palette (themes/<name>.sh) and regenerates the color files that
# each app's config consumes, then live-reloads everything.
#
# Usage:
#   theme-switch.sh nord|gruvbox|latte   # set a specific theme
#   theme-switch.sh next                  # cycle to the next theme
#   theme-switch.sh                       # re-apply the current theme
#
set -euo pipefail

DOTFILES="${DOTFILES:-$HOME/dotfiles}"
THEMES_DIR="$DOTFILES/themes"
STATE_FILE="$HOME/.config/sway/.current-theme"
CYCLE=(nord gruvbox latte)

usage() {
    echo "Usage: $(basename "$0") [${CYCLE[*]// /|}|next]"
    echo "Available themes:"
    for t in "$THEMES_DIR"/*.sh; do echo "  - $(basename "${t%.sh}")"; done
    exit 1
}

choice="${1:-$(cat "$STATE_FILE" 2>/dev/null || echo nord)}"

# "next" cycles through the list
if [ "$choice" = "next" ]; then
    current="$(cat "$STATE_FILE" 2>/dev/null || echo "${CYCLE[0]}")"
    idx=0
    for i in "${!CYCLE[@]}"; do [ "${CYCLE[$i]}" = "$current" ] && idx=$i; done
    choice="${CYCLE[$(((idx + 1) % ${#CYCLE[@]}))]}"
fi

PALETTE="$THEMES_DIR/$choice.sh"
[ -f "$PALETTE" ] || { echo "[x] Theme '$choice' not found."; usage; }

# shellcheck source=/dev/null
source "$PALETTE"

mkdir -p "$HOME/.config/waybar" "$HOME/.config/rofi" \
         "$HOME/.config/kitty" "$HOME/.config/sway" "$HOME/.config/mako"

# Break any symlink first so we write real files in ~/.config (never through a
# symlink back into the dotfiles repo, which would dirty git on every switch).
rm -f "$HOME/.config/waybar/colors.css" "$HOME/.config/rofi/colors.rasi" \
      "$HOME/.config/kitty/matugen.conf" "$HOME/.config/sway/colors.conf" \
      "$HOME/.config/mako/config"

# ── waybar (Material-style vars, matches style.css) ──
cat > "$HOME/.config/waybar/colors.css" <<EOF
/* generated by theme-switch.sh — theme: $choice — do not edit by hand */
@define-color surface           $SURFACE;
@define-color surface_container $BG_ALT;
@define-color surface_bright    $BG_BRIGHT;
@define-color on_surface        $FG;
@define-color primary           $ACCENT;
@define-color on_primary        $ON_ACCENT;
@define-color secondary         $SECONDARY;
@define-color tertiary          $TERTIARY;
@define-color error             $ERROR;
@define-color outline           $FG_ALT;
@define-color outline_variant   $BORDER;
EOF

# ── rofi ──
cat > "$HOME/.config/rofi/colors.rasi" <<EOF
/* generated by theme-switch.sh — theme: $choice — do not edit by hand */
* {
    bg:          $BG;
    bg-alt:      $BG_ALT;
    fg:          $FG;
    fg-alt:      $FG_ALT;
    accent:      $ACCENT;
    border:      $ACCENT;
    transparent: transparent;
}
EOF

# ── kitty (reuses the `include matugen.conf` slot already in kitty.conf;
#    on Debian/sway matugen isn't used, so this file holds the active theme) ──
cat > "$HOME/.config/kitty/matugen.conf" <<EOF
# generated by theme-switch.sh — theme: $choice — do not edit by hand
foreground $FG
background $BG
cursor     $ACCENT
selection_background $BG_BRIGHT
selection_foreground $FG
color0  $COL0
color1  $COL1
color2  $COL2
color3  $COL3
color4  $COL4
color5  $COL5
color6  $COL6
color7  $COL7
color8  $COL8
color9  $COL9
color10 $COL10
color11 $COL11
color12 $COL12
color13 $COL13
color14 $COL14
color15 $COL15
EOF

# ── sway (included by ~/.config/sway/config) ──
cat > "$HOME/.config/sway/colors.conf" <<EOF
# generated by theme-switch.sh — theme: $choice — do not edit by hand
set \$accent   $ACCENT
set \$bg       $BG
set \$bg_alt   $BG_ALT
set \$fg       $FG
set \$inactive $BORDER_INACTIVE
set \$urgent   $ERROR
EOF

# ── mako (no @import support → regenerate the whole config) ──
cat > "$HOME/.config/mako/config" <<EOF
# generated by theme-switch.sh — theme: $choice — do not edit by hand
font=IosevkaTerm Nerd Font 11
background-color=${BG_ALT}f2
text-color=$FG
border-color=$ACCENT
progress-color=over $BG_BRIGHT
border-size=2
border-radius=8
padding=10
margin=8
default-timeout=5000
max-visible=5
anchor=top-right

[urgency=high]
border-color=$ERROR
default-timeout=0
EOF

# ── persist + live reload ──
echo "$choice" > "$STATE_FILE"
swaymsg reload          >/dev/null 2>&1 || true
makoctl reload          >/dev/null 2>&1 || true
pkill -SIGUSR1 -x kitty >/dev/null 2>&1 || true   # kitty live config reload
command -v notify-send >/dev/null 2>&1 && notify-send -t 2000 "Theme" "Switched to $choice" || true

echo "[+] Theme applied: $choice"
